name: Deploy React Frontend to EC2

on:
  push:
    branches:
      - main  # Asosiy branch nomi, kerak bo'lsa o'zgartir

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
       run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@51.21.243.235 << 'EOF'
          cd ~/frontend
          git pull origin main
          npm install
          npm run build

          # Build qilingan fayllarni nginx ko‘radigan joyga ko‘chirish
          sudo rm -rf /var/www/html/*
          sudo cp -r build/* /var/www/html/
        EOF
